# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: TerraformBlueprint
metadata:
  name: terraform-google-network-security-authorization-policy
  source:
    type: git
    location: https://github.com/GoogleCloudPlatform/terraform-google-network-security-authorization-policy.git
  version: 1.0.0
  actuationTool:
    type: Terraform
    version: '>= 1.3'
  title: Network Security Authorization Policy
  description:
    tagline: A Terraform module to create a Google Cloud Network Security Authorization Policy.
    detailed: This module handles the creation and configuration of a google_network_security_authorization_policy, which defines a policy that can be used to authorize connections for services like HTTPS Load Balancers.
spec:
  terraform:
    variables:
      - name: action
        description: The action to take when a rule is matched. Possible values are "ALLOW" or "DENY".
        type: string
        default: "ALLOW"
        required: false
      - name: description
        description: A free-text description of the resource.
        type: string
        default: null
        required: false
      - name: labels
        description: Set of label tags associated with the authorization policy.
        type: map(string)
        default: null
        required: false
      - name: location
        description: The location of the authorization policy.
        type: string
        default: "global"
        required: false
      - name: name
        description: The name of the authorization policy. A unique name is required for each authorization policy in a project and location. If not provided, a random name will be generated.
        type: string
        default: null
        required: false
      - name: project_id
        description: The ID of the project in which the resource belongs. If not provided, the provider project is used.
        type: string
        default: null
        required: false
      - name: rules
        description: |
          A list of rules that specify the matching criteria for the authorization policy. Each rule is an object with the following attributes:
          - `sources`: (Optional) A list of source objects. Each source object can have the following attributes:
            - `principals`: (Optional) A list of peer identities to match for the source.
            - `ip_blocks`: (Optional) A list of CIDR ranges to match for the source.
          - `destinations`: (Optional) A list of destination objects. Each destination object can have the following attributes:
            - `hosts`: (Required) A list of host names to match in HTTP 'Host' header.
            - `ports`: (Required) A list of port numbers to match on the destination.
            - `methods`: (Optional) A list of HTTP methods to match.
            - `http_header_match`: (Optional) An object specifying HTTP header match attributes:
              - `header_name`: (Required) The name of the HTTP header to match.
              - `regex_match`: (Required) The value of the header must match the regular expression.
        type: list(object)
        default: []
        required: false
    outputs:
      - name: create_time
        description: The time when the authorization policy was created.
      - name: id
        description: The fully qualified ID of the authorization policy.
      - name: name
        description: The name of the authorization policy.
  requirements:
    services:
      - networksecurity.googleapis.com
    roles:
      - role: roles/networksecurity.admin
        level: project
