# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: TerraformBlueprint
metadata:
  name: terraform-google-network-services-authz-extension
  source:
    type: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-network-services-authz-extension.git
      dir: /
  version: 0.1.0
  title: Network Services Authorization Extension
  descriptions:
    tagline: Creates a `google_network_services_authz_extension` resource for flexible authorization policies in a service mesh.
    detailed: |
      This module creates a `google_network_services_authz_extension` resource.
      This resource allows for flexible authorization policies in a service mesh
      using an external gRPC authorizer, enabling advanced security configurations
      for managed services.
  actuationTool:
    type: Terraform
    versions:
    - ">= 1.3"
spec:
  requirements:
    services:
    - networkservices.googleapis.com
    roles:
    - level: project
      roles:
      - roles/networkservices.authzExtensionAdmin
  customization:
    variables:
    - name: authority
      description: "Required. The authority header of the gRPC request."
      type: string
      required: false
      default: "authz-ext.example.com"
    - name: description
      description: "A free-text description of the resource."
      type: string
      required: false
      default: null
    - name: labels
      description: "A set of key/value label pairs to assign to the resource."
      type: map(string)
      required: false
      default: {}
    - name: load_balancing_scheme
      description: "The load balancing scheme for which the AuthzExtension is applicable. Must be one of `INTERNAL_MANAGED` or `EXTERNAL_MANAGED`."
      type: string
      required: false
      default: "INTERNAL_MANAGED"
    - name: location
      description: "The location of the AuthzExtension resource."
      type: string
      required: false
      default: "global"
    - name: name
      description: "The name of the AuthzExtension resource."
      type: string
      required: false
      default: "my-authz-extension"
    - name: project_id
      description: "The ID of the project in which the resource belongs. If not provided, the provider project is used."
      type: string
      required: false
      default: null
    - name: service
      description: "The name of a BackendService that services the requests of the ext_authz gRPC authorization service. The format is `projects/{project}/global/backendServices/{backendService}`."
      type: string
      required: false
      default: "projects/project-id/global/backendServices/backend-service-name"
    - name: timeout
      description: "Required. The timeout for the authorization check. A duration in seconds with up to nine fractional digits, ending with 's'. Example: \"3.5s\"."
      type: string
      required: false
      default: "10s"
    outputs:
    - name: create_time
      description: "The timestamp when the resource was created."
    - name: id
      description: "The fully qualified identifier of the AuthzExtension resource."
    - name: name
      description: "The name of the created AuthzExtension resource."
    - name: update_time
      description: "The timestamp when the resource was last updated."
